import type { TripJourney } from '@/types/database.types';

export const MOCK_JOURNEYS: TripJourney[] = [
  {
    id: 'jrn_goa_01',
    traveler_id: 'usr_traveler_01',
    operator_id: 'usr_operator_01',
    coordinator_id: 'usr_coord_01',
    title: 'Goa Getaway',
    destination_ids: ['dest_goa_01'],
    start_date: '12 May 2025',
    end_date: '16 May 2025',
    duration_days: 5,
    duration_nights: 4,
    travelers_count: 2,
    total_budget: 40000,
    currency: 'INR',
    status: 'active',
    current_location: 'Candolim & Panjim, North Goa',
    passport_reference_code: 'GOA250512<<5D4N<<ADVENTURE<<<<<<<<<<<<<',
    hero_image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&q=80&w=1200',
    travel_styles: ['Adventure', 'Beaches', 'Food'],
    progress_percentage: 80,
    bookings_count: 8,
    next_activity: '12 May • 14:00 Check-in at Seashell Resort',
    last_updated: '10 mins ago',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'jrn_kashmir_01',
    traveler_id: 'usr_traveler_01',
    operator_id: 'usr_operator_01',
    title: 'Kashmir Escape',
    destination_ids: ['dest_kashmir_01'],
    start_date: '20 May 2025',
    end_date: '26 May 2025',
    duration_days: 7,
    duration_nights: 6,
    travelers_count: 2,
    total_budget: 68000,
    currency: 'INR',
    status: 'planning',
    current_location: 'Dal Lake & Gulmarg',
    passport_reference_code: 'KSH250520<<7D6N<<NATURE<<<<<<<<<<<<<<<',
    hero_image: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&q=80&w=800',
    travel_styles: ['Nature', 'Mountains', 'Culture'],
    progress_percentage: 45,
    bookings_count: 5,
    next_activity: '20 May • 11:30 Shikara Cruise Arrival',
    last_updated: '2 hours ago',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'jrn_rajasthan_01',
    traveler_id: 'usr_traveler_01',
    operator_id: 'usr_operator_01',
    title: 'Rajasthan Heritage Tour',
    destination_ids: ['dest_rajasthan_01'],
    start_date: '10 Jun 2025',
    end_date: '15 Jun 2025',
    duration_days: 6,
    duration_nights: 5,
    travelers_count: 4,
    total_budget: 92000,
    currency: 'INR',
    status: 'planning',
    current_location: 'Jaipur, Jodhpur & Udaipur',
    passport_reference_code: 'RAJ250610<<6D5N<<HERITAGE<<<<<<<<<<<<<',
    hero_image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&q=80&w=800',
    travel_styles: ['Heritage', 'Culture', 'Architecture'],
    progress_percentage: 20,
    bookings_count: 3,
    next_activity: '10 Jun • Amber Fort Sunrise Access',
    last_updated: '1 day ago',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'jrn_dubai_01',
    traveler_id: 'usr_traveler_01',
    title: 'Dubai Break',
    destination_ids: ['dest_dubai_01'],
    start_date: '5 Jul 2025',
    end_date: '8 Jul 2025',
    duration_days: 4,
    duration_nights: 3,
    travelers_count: 2,
    total_budget: 85000,
    currency: 'INR',
    status: 'draft',
    current_location: 'Downtown & Marina, Dubai',
    passport_reference_code: 'DXB250705<<4D3N<<LUXURY<<<<<<<<<<<<<<<',
    hero_image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&q=80&w=800',
    travel_styles: ['Luxury', 'Skyline', 'Shopping'],
    progress_percentage: 10,
    bookings_count: 1,
    next_activity: 'Select Desert Safari Option',
    last_updated: '3 days ago',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'jrn_kerala_01',
    traveler_id: 'usr_traveler_01',
    operator_id: 'usr_operator_01',
    title: 'Kerala Serenity Voyage',
    destination_ids: ['dest_kerala_01'],
    start_date: '14 Aug 2025',
    end_date: '19 Aug 2025',
    duration_days: 6,
    duration_nights: 5,
    travelers_count: 2,
    total_budget: 54000,
    currency: 'INR',
    status: 'planning',
    current_location: 'Alleppey & Munnar Hills',
    passport_reference_code: 'KER250814<<6D5N<<BACKWATERS<<<<<<<<<<<',
    hero_image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&q=80&w=800',
    travel_styles: ['Backwaters', 'Wellness', 'Nature'],
    progress_percentage: 35,
    bookings_count: 4,
    next_activity: 'Confirm Houseboat Upgrade',
    last_updated: '5 days ago',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export class JourneyService {
  public static async getAll(): Promise<TripJourney[]> {
    return MOCK_JOURNEYS;
  }

  public static async getActiveJourney(): Promise<TripJourney | null> {
    return MOCK_JOURNEYS[0] || null;
  }

  public static async getById(id: string): Promise<TripJourney | null> {
    return MOCK_JOURNEYS.find((j) => j.id === id) || MOCK_JOURNEYS[0];
  }
}
